version = 0.1

[default.deploy.parameters]
stack_name = "{{ cookiecutter.function_name }}"
region = "{{ cookiecutter.aws_region }}"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
