name: CI
on: pull_request

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build sosw docs
      run: sudo apt-get install python3-sphinx; sphinx-build -ab html ./docs ./sosw-rtd
#
#    - name: Sync files to s3
#      uses: cd sosw-rtd; aws s3 sync . s3://test-s3-for-sosw
